// <auto-generated />
namespace Infrastructure.Persistance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddConfiguracioSistemasContpaqi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddConfiguracioSistemasContpaqi));
        
        string IMigrationMetadata.Id
        {
            get { return "202003100522209_AddConfiguracioSistemasContpaqi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
